// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lv_delta_cor
arma::mat lv_delta_cor(const arma::mat& e, const arma::mat& d, int nthreads);
RcppExport SEXP _Loopvelocity_lv_delta_cor(SEXP eSEXP, SEXP dSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_delta_cor(e, d, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_delta_cor_sqrt
arma::mat lv_delta_cor_sqrt(const arma::mat& e, const arma::mat& d, int nthreads);
RcppExport SEXP _Loopvelocity_lv_delta_cor_sqrt(SEXP eSEXP, SEXP dSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_delta_cor_sqrt(e, d, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_delta_cor_log10
arma::mat lv_delta_cor_log10(const arma::mat& e, const arma::mat& d, double pseudocount, int nthreads);
RcppExport SEXP _Loopvelocity_lv_delta_cor_log10(SEXP eSEXP, SEXP dSEXP, SEXP pseudocountSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_delta_cor_log10(e, d, pseudocount, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_col_euclid
arma::mat lv_col_euclid(const arma::mat& e, const arma::mat& p, int nthreads);
RcppExport SEXP _Loopvelocity_lv_col_euclid(SEXP eSEXP, SEXP pSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_col_euclid(e, p, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_emb_arrows
arma::mat lv_emb_arrows(const arma::mat& emb, const arma::sp_mat& tp, double arrow_scale, int nthreads);
RcppExport SEXP _Loopvelocity_lv_emb_arrows(SEXP embSEXP, SEXP tpSEXP, SEXP arrow_scaleSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type emb(embSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type arrow_scale(arrow_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_emb_arrows(emb, tp, arrow_scale, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_wls_fit
List lv_wls_fit(NumericVector x, NumericVector y, NumericVector w);
RcppExport SEXP _Loopvelocity_lv_wls_fit(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_wls_fit(x, y, w));
    return rcpp_result_gen;
END_RCPP
}
// lv_col_cor
arma::mat lv_col_cor(const arma::mat& m);
RcppExport SEXP _Loopvelocity_lv_col_cor(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_col_cor(m));
    return rcpp_result_gen;
END_RCPP
}
// lv_insulation_score
NumericVector lv_insulation_score(const NumericMatrix& m, int window);
RcppExport SEXP _Loopvelocity_lv_insulation_score(SEXP mSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_insulation_score(m, window));
    return rcpp_result_gen;
END_RCPP
}
// lv_window_contacts
double lv_window_contacts(IntegerVector bin1, IntegerVector bin2, NumericVector count, double bin_start, double bin_size, double flank);
RcppExport SEXP _Loopvelocity_lv_window_contacts(SEXP bin1SEXP, SEXP bin2SEXP, SEXP countSEXP, SEXP bin_startSEXP, SEXP bin_sizeSEXP, SEXP flankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bin1(bin1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bin2(bin2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type bin_start(bin_startSEXP);
    Rcpp::traits::input_parameter< double >::type bin_size(bin_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type flank(flankSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_window_contacts(bin1, bin2, count, bin_start, bin_size, flank));
    return rcpp_result_gen;
END_RCPP
}
// lv_balanced_knn_graph
arma::sp_mat lv_balanced_knn_graph(const arma::mat& d, int k, int maxl, bool return_distance_values, int nthreads);
RcppExport SEXP _Loopvelocity_lv_balanced_knn_graph(SEXP dSEXP, SEXP kSEXP, SEXP maxlSEXP, SEXP return_distance_valuesSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxl(maxlSEXP);
    Rcpp::traits::input_parameter< bool >::type return_distance_values(return_distance_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_balanced_knn_graph(d, k, maxl, return_distance_values, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// lv_two_sided_solution
List lv_two_sided_solution(NumericVector t, double alpha, double theta, double gamma);
RcppExport SEXP _Loopvelocity_lv_two_sided_solution(SEXP tSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_two_sided_solution(t, alpha, theta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// lv_one_sided_solution
List lv_one_sided_solution(NumericVector t, double alpha, double beta, double gamma);
RcppExport SEXP _Loopvelocity_lv_one_sided_solution(SEXP tSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_one_sided_solution(t, alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// lv_em_objective_two_sided
double lv_em_objective_two_sided(NumericVector t, NumericVector Sobs, NumericVector Iobs, NumericVector phi);
RcppExport SEXP _Loopvelocity_lv_em_objective_two_sided(SEXP tSEXP, SEXP SobsSEXP, SEXP IobsSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sobs(SobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Iobs(IobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_em_objective_two_sided(t, Sobs, Iobs, phi));
    return rcpp_result_gen;
END_RCPP
}
// lv_em_objective_one_sided
double lv_em_objective_one_sided(NumericVector t, NumericVector Sobs, NumericVector Iobs, NumericVector phi);
RcppExport SEXP _Loopvelocity_lv_em_objective_one_sided(SEXP tSEXP, SEXP SobsSEXP, SEXP IobsSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sobs(SobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Iobs(IobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_em_objective_one_sided(t, Sobs, Iobs, phi));
    return rcpp_result_gen;
END_RCPP
}
// lv_project_two_sided
NumericVector lv_project_two_sided(NumericVector Iobs, double theta, double gamma, double delta_t, double alpha);
RcppExport SEXP _Loopvelocity_lv_project_two_sided(SEXP IobsSEXP, SEXP thetaSEXP, SEXP gammaSEXP, SEXP delta_tSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Iobs(IobsSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type delta_t(delta_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(lv_project_two_sided(Iobs, theta, gamma, delta_t, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Loopvelocity_lv_delta_cor", (DL_FUNC) &_Loopvelocity_lv_delta_cor, 3},
    {"_Loopvelocity_lv_delta_cor_sqrt", (DL_FUNC) &_Loopvelocity_lv_delta_cor_sqrt, 3},
    {"_Loopvelocity_lv_delta_cor_log10", (DL_FUNC) &_Loopvelocity_lv_delta_cor_log10, 4},
    {"_Loopvelocity_lv_col_euclid", (DL_FUNC) &_Loopvelocity_lv_col_euclid, 3},
    {"_Loopvelocity_lv_emb_arrows", (DL_FUNC) &_Loopvelocity_lv_emb_arrows, 4},
    {"_Loopvelocity_lv_wls_fit", (DL_FUNC) &_Loopvelocity_lv_wls_fit, 3},
    {"_Loopvelocity_lv_col_cor", (DL_FUNC) &_Loopvelocity_lv_col_cor, 1},
    {"_Loopvelocity_lv_insulation_score", (DL_FUNC) &_Loopvelocity_lv_insulation_score, 2},
    {"_Loopvelocity_lv_window_contacts", (DL_FUNC) &_Loopvelocity_lv_window_contacts, 6},
    {"_Loopvelocity_lv_balanced_knn_graph", (DL_FUNC) &_Loopvelocity_lv_balanced_knn_graph, 5},
    {"_Loopvelocity_lv_two_sided_solution", (DL_FUNC) &_Loopvelocity_lv_two_sided_solution, 4},
    {"_Loopvelocity_lv_one_sided_solution", (DL_FUNC) &_Loopvelocity_lv_one_sided_solution, 4},
    {"_Loopvelocity_lv_em_objective_two_sided", (DL_FUNC) &_Loopvelocity_lv_em_objective_two_sided, 4},
    {"_Loopvelocity_lv_em_objective_one_sided", (DL_FUNC) &_Loopvelocity_lv_em_objective_one_sided, 4},
    {"_Loopvelocity_lv_project_two_sided", (DL_FUNC) &_Loopvelocity_lv_project_two_sided, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Loopvelocity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
