# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lv_delta_cor <- function(e, d, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_delta_cor`, e, d, nthreads)
}

lv_delta_cor_sqrt <- function(e, d, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_delta_cor_sqrt`, e, d, nthreads)
}

lv_delta_cor_log10 <- function(e, d, pseudocount = 1.0, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_delta_cor_log10`, e, d, pseudocount, nthreads)
}

lv_col_euclid <- function(e, p, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_col_euclid`, e, p, nthreads)
}

lv_emb_arrows <- function(emb, tp, arrow_scale = 1.0, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_emb_arrows`, emb, tp, arrow_scale, nthreads)
}

#' Weighted least squares fit of the steady-state constraint
#'
#' Closed-form weighted linear regression y ~ a + b*x used for the per-TAD
#' steady-state fits (Eq 13/14). Weights are 0/1 selections of top/bottom
#' quantile cells.
#' @param x,y numeric vectors (I and S boundary contacts)
#' @param w nonnegative weights
#' @return list with \code{intercept} and \code{slope}
#' @examples
#' x <- 1:10; y <- 2 * x + 1
#' lv_wls_fit(x, y, rep(1, 10))
#' @export
lv_wls_fit <- function(x, y, w) {
    .Call(`_Loopvelocity_lv_wls_fit`, x, y, w)
}

#' Pairwise correlations of matrix columns
#'
#' @param m dense numeric matrix
#' @return correlation matrix
#' @examples
#' m <- matrix(rnorm(30), ncol = 3)
#' lv_col_cor(m)
#' @export
lv_col_cor <- function(m) {
    .Call(`_Loopvelocity_lv_col_cor`, m)
}

#' Diamond insulation score
#'
#' Mean contact frequency in the lower diamond of radius \code{window}
#' around each bin of a contact matrix; bins near the matrix edges are NA.
#' Local minima of this score mark candidate TAD boundaries.
#'
#' @param m square dense contact matrix
#' @param window diamond radius in bins
#' @return numeric vector of insulation scores per bin
#' @examples
#' m <- matrix(1, 10, 10)            # uniform contacts: flat profile
#' lv_insulation_score(m, window = 2)[3:8]
#' @export
lv_insulation_score <- function(m, window) {
    .Call(`_Loopvelocity_lv_insulation_score`, m, window)
}

#' Total contacts with at least one endpoint inside a boundary window
#'
#' The window spans [bin_start - flank, bin_start + bin_size + flank);
#' bins are 1-based, positions derived as (bin - 1) * bin_size.
#'
#' @param bin1,bin2 integer vectors of pixel endpoint bins
#' @param count pixel counts
#' @param bin_start genomic start (bp) of the boundary bin
#' @param bin_size bin resolution (bp)
#' @param flank window extension on both sides (bp)
#' @return total contact count touching the window
#' @examples
#' lv_window_contacts(c(1L, 4L, 9L), c(2L, 5L, 10L), c(2, 3, 4),
#'                    bin_start = 4000, bin_size = 1000, flank = 1500)
#' @export
lv_window_contacts <- function(bin1, bin2, count, bin_start, bin_size, flank) {
    .Call(`_Loopvelocity_lv_window_contacts`, bin1, bin2, count, bin_start, bin_size, flank)
}

lv_balanced_knn_graph <- function(d, k, maxl, return_distance_values = FALSE, nthreads = 1L) {
    .Call(`_Loopvelocity_lv_balanced_knn_graph`, d, k, maxl, return_distance_values, nthreads)
}

lv_two_sided_solution <- function(t, alpha, theta, gamma) {
    .Call(`_Loopvelocity_lv_two_sided_solution`, t, alpha, theta, gamma)
}

lv_one_sided_solution <- function(t, alpha, beta, gamma) {
    .Call(`_Loopvelocity_lv_one_sided_solution`, t, alpha, beta, gamma)
}

lv_em_objective_two_sided <- function(t, Sobs, Iobs, phi) {
    .Call(`_Loopvelocity_lv_em_objective_two_sided`, t, Sobs, Iobs, phi)
}

lv_em_objective_one_sided <- function(t, Sobs, Iobs, phi) {
    .Call(`_Loopvelocity_lv_em_objective_one_sided`, t, Sobs, Iobs, phi)
}

lv_project_two_sided <- function(Iobs, theta, gamma, delta_t, alpha) {
    .Call(`_Loopvelocity_lv_project_two_sided`, Iobs, theta, gamma, delta_t, alpha)
}

